### ISSUE TITLE
Question of optimization (over bootstrapped ?)

### ISSUE THREAD

**Issue by JOduMonT** [hibbitts-design/grav-skeleton-course-hub#2]
Hi Paul;

I was reviewing my_theme based on your skeleton with lighthouse
and I think the boostrap css is over loaded mostly because
1. the bootstrap4 load is own compiled css
2. than open matter load bootswatch
3. than by default the bootstrap plugin load bootstrap via CDN

![untitled](https://user-images.githubusercontent.com/5204724/47282880-23d01f00-d5e1-11e8-995b-380dc9fad6c5.jpg)

I'm not a webdev but I think It worth to disable the `Load Core CSS` in the bootstrap plugin and/or put a if somewhere....

what do you think ?

**Comment by paulhibbitts** [comment]
Hi @jodumont, you could try to disable the 'Always Load' option in the Bootstrapper Plugin and see if that might remove load item #3. I have not intended to cause any more CSS loads with the theme, so I am not sure why it looks to load Bootstrap twice - if I understand correctly.

**Comment by JOduMonT** [comment]
Indeed; I change these 2 options in the Bootstrapper Plugin and it do the job

I was just wondering if it should be by default or not.

In any case, it is your decision;
I'll close this issue which was more to notice you to be aware of, than anything else.

**Comment by paulhibbitts** [comment]
Thanks for the heads-up about this issue @jodumont , I plan to explore this further esp. since I intended that the Bootstrapper Plugin would load the one and only bootstrap CSS.

UPDATE: It looks like when I added the ability to use Bootswatch theme styles I also added a load of the default Bootstrap CSS. So, in the short-term disabling the 'Load CSS' option from the Bootstrapper plugin is the best way to address this issue. I will also make this the default setting in my Bootstrap4 Open Course Hub skeleton.
